name=LoRaMESH
version=1.0.0
author=Gustavo Cereza
maintainer=Gustavo Cereza
sentence=Library to interface with Radioenge LoRaMESH modules over UART.
paragraph=Portable C++ library for Radioenge LoRaMESH modules supporting command and transparent modes across Arduino, ESP-IDF, STM32 and Linux.
category=Communication
url=https://github.com/elcereza/LoRaMESH
architectures=*